stages:
  processing:
    cmd: python src/processing.py data/raw/titanic.csv 
      data/processed/titanic.csv
    deps:
    - data/raw/titanic.csv
    - src/processing.py
    outs:
    - data/processed/titanic.csv
  training:
    cmd: python src/training.py data/processed/titanic.csv
    deps:
    - data/processed/titanic.csv
    - src/training.py
