reproductibility:
  random_state: 42
data:
  path:
    raw: data/raw/titanic.csv
    processed: data/processed/titanic.csv
  processing:
    columns_to_remove:
    - Name
    - Ticket
    - Cabin
    - PassengerId
training:
  test_size: 0.2
  target_col: Survived
  max_depth: 8
  impute_num_strategy: median
  impute_cat_strategy: most_frequent
  n_split: 3
  scoring: f1_macro
gx:
  context_root_dir: great_expectations
  suite_name: titanic_raw_suite
  data_source: titanic_datasource
  asset_name: titanic_raw
  batch_definition_name: titanic.csv
