name: titanic mlops CI

on: 
  push: 
    branches: [main]


jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: get python code
        uses: actions/checkout@v6

      - name: setup python code
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install dependencies
        run: |
          python -m pip install pip --upgrade
          pip install -r requirements.txt

      - name: configuration dvc
        run: |
          dvc remote modify --local r2remote access_key_id ${{ secrets.R2_ACCESS_KEY }}
          dvc remote modify --local r2remote secret_access_key ${{ secrets.R2_SECRET_KEY }}

      - name: pull existing data
        run: |
          dvc pull
          
      - name: validate data raw
        run: | 
          echo "Validation..."
          python src/validation.py
          echo "Validation successful !"

      - name: run tests
        run: | 
          echo "Testing..."
          pytest tests/ -v

      - name: training
        run: |
          echo "Training"
          dvc repro --force
          echo "training complete !"

      - name: push dvc artifact to remote
        if: github.ref == "refs/heads/main"
        run: |
          dvc push
          echo "pushing complete"
      
